name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # Make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  # Make sure the action works on a clean machine without building.
  e2e:
    if: github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs: build # Wait for the other job to finish so we have some logs to fetch.
    steps:
      - name: checkout
        uses: actions/checkout@v2
      ## test loki logs
      - name: loki-action
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          endpoint: ${{ secrets.LOGQL_ENDPOINT || 'https://cloki.glitch.me' }}
          job-names: build
      ## test elastic logs
      - name: elastic-logs
        if: failure()
        uses: metrico/opensearch-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          addresses:  ${{ secrets.LOGQL_ENDPOINT || 'https://cloki.glitch.me' }}
          job-names: build
